:hide-uri-scheme:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc:

= Participating in RNRH development

== Initializing the project

Clone the project:
```
git clone git@github.com:meliorence/react-native-render-html.git
```
Then yarn-install:
```
cd react-native-render-html
yarn install
```

== Package sources

Package sources are located in `packages/render-html`.


== Scripts

The project is using
Yarn Berry's workspaces. There is an alias to work from
`react-native-render-html` workspace:

```
yarn render-html
```

You can then run the following commands:

[cols="1,1"]
|===
| Most significant scripts
| Description

| `yarn render-html test:jest --watch`
| Launch jest test in watch mode

| `yarn render-html test:ts`
| Run Typescript typechecking

| `yarn render-html test:lint`
| Run linter

| `yarn render-html build`
| Transpile TS → ES
|===

== Demo app

```
yarn build:tools
yarn render-html build
```

From now-on, you should be able to try out the demo app with
```
yarn demo start
```

== Documentation

All the doc pages are React components available in
`doc-tools/doc-pages/src/pages` and are built for both the Discovery expo app
and website.